// AllAssociationCard.jsx
export const allFarmers = [
  {
    name: "Pantok Farmers Association",
    location: "Pantok, Binangonan",
    sold: "10k",
    rank: 2,
    categories: ["milks & dairy", "rice", "grains"],
    img: "/555.png",
    gridImg: "/Pantok.png",
    place: "Pantok",
    followers: 245,
    rating: 5.0,
    responseRate: "95%",
    productsSold: "10k"
  },
  {
    name: "Macamot Farmers Association",
    location: "Macamot, Binangonan",
    sold: "12k",
    rank: 1,
    categories: ["fruits", "rice", "vegetables", "root crops"],
    img: "/444.png",
    gridImg: "/Macamot.png",
    place: "Macamot",
    followers: 312,
    rating: 4.9,
    responseRate: "98%",
    productsSold: "12k"
  },
  {
    name: "Tagpos Farmers Association",
    location: "Tagpos, Binangonan",
    sold: "9k",
    rank: 3,
    categories: ["fruits", "root crops", "meat"],
    img: "/222.png",
    gridImg: "/Tagpos.png",
    place: "Tagpos",
    followers: 198,
    rating: 4.8,
    responseRate: "92%",
    productsSold: "9k"
  },
  {
    name: "Bilibiran Farmers Association",
    location: "Bilibiran, Binangonan",
    sold: "8k",
    rank: 4,
    categories: ["vegetables", "grains"],
    img: "/Bilibiran.png",
    place: "Bilibiran",
    followers: 167,
    rating: 4.7,
    responseRate: "90%",
    productsSold: "8k"
  },
  {
    name: "Samahang Magsasaka ng Darangan",
    location: "Darangan, Binangonan",
    sold: "7k",
    rank: 5,
    categories: ["fruits", "vegetables"],
    img: "/Darangan.png",
    place: "Darangan",
    followers: 134,
    rating: 4.6,
    responseRate: "88%",
    productsSold: "7k"
  },
  {
    name: "Hulo Farmers Association",
    location: "Hulo, Binangonan",
    sold: "6k",
    rank: 6,
    categories: ["rice", "root crops"],
    img: "/Hulo.png",
    place: "Hulo",
    followers: 123,
    rating: 4.5,
    responseRate: "85%",
    productsSold: "6k"
  },
  {
    name: "Pugad St. Monique Farmers Association",
    location: "Pugad, Binangonan",
    sold: "5k",
    rank: 7,
    categories: ["vegetables", "fruits"],
    img: "/Pugad.png",
    place: "Pugad",
    followers: 98,
    rating: 4.4,
    responseRate: "82%",
    productsSold: "5k"
  },
  {
    name: "Tabing Dagat Farmers Association",
    location: "T.Dagat, Binangonan",
    sold: "4k",
    rank: 8,
    categories: ["meat", "milks & dairy"],
    img: "/Tabingdagat.png",
    place: "T.Dagat",
    followers: 87,
    rating: 4.3,
    responseRate: "80%",
    productsSold: "4k"
  },
  {
    name: "Kaykansa Farmers Collective",
    location: "Kaykansa, Binangonan",
    sold: "3k",
    rank: 9,
    categories: ["grains", "vegetables"],
    img: "/Kaykansa.png",
    place: "Kaykansa",
    followers: 76,
    rating: 4.2,
    responseRate: "78%",
    productsSold: "3k"
  },
  {
    name: "Kaysapon Agricultural Society",
    location: "Kaysapon, Binangonan",
    sold: "2k",
    rank: 10,
    categories: ["fruits", "root crops"],
    img: "/Kaysapon.png",
    place: "Kaysapon",
    followers: 65,
    rating: 4.1,
    responseRate: "75%",
    productsSold: "2k"
  },
  {
    name: "Kaymaputi Farmers Guild",
    location: "Kaymaputi, Binangonan",
    sold: "1.5k",
    rank: 11,
    categories: ["rice", "grains"],
    img: "/Kaymaputi.png",
    place: "Kaymaputi",
    followers: 54,
    rating: 4.0,
    responseRate: "72%",
    productsSold: "1.5k"
  },
  {
    name: "Pila-pila Farmers Association",
    location: "Pila-pila, Binangonan",
    sold: "1k",
    rank: 12,
    categories: ["vegetables", "milks & dairy"],
    img: "/pila-pila.png",
    place: "Pila-pila",
    followers: 43,
    rating: 3.9,
    responseRate: "70%",
    productsSold: "1k"
  },
  {
    name: "Calumpang Farmers Association",
    location: "Calumpang, Binangonan",
    sold: "900",
    rank: 13,
    categories: ["fruits", "meat"],
    img: "/calumpang.png",
    place: "Calumpang",
    followers: 32,
    rating: 3.8,
    responseRate: "68%",
    productsSold: "900"
  },
  {
    name: "Halang Integrated Farmers Association",
    location: "Halang, Binangonan",
    sold: "800",
    rank: 14,
    categories: ["root crops", "vegetables"],
    img: "/Halang.png",
    place: "Halang",
    followers: 21,
    rating: 3.7,
    responseRate: "65%",
    productsSold: "800"
  },
  {
    name: "Tatala Farmers Association",
    location: "Tatala, Binangonan",
    sold: "700",
    rank: 15,
    categories: ["grains", "rice"],
    img: "/tatala.png",
    place: "Tatala",
    followers: 18,
    rating: 3.6,
    responseRate: "62%",
    productsSold: "700"
  },
  {
    name: "Mambog Farmers Association",
    location: "Mambog, Binangonan",
    sold: "600",
    rank: 16,
    categories: ["fruits", "vegetables"],
    img: "/mambog.png",
    place: "Mambog",
    followers: 15,
    rating: 3.5,
    responseRate: "60%",
    productsSold: "600"
  }
];